name: dunno_hack
description: Play trivia by yourself or with friends using questions from Open Trivia Database

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  file_picker: ^4.2.7
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.2.0
  html_character_entities: ^1.0.0+1
  http: ^0.13.4
  rxdart: ^0.27.2
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
